`define PRESCALER_RESET_VAL 5'd1
`define PERIOD_RESET_VAL 16'd10
`define START_RESET_VAL 1'd0
`define DUTY_RESET_VAL 16'd5 

`define PRESCALER_ADDR 2'b10
`define PERIOD_ADDR 2'b00
`define START_ADDR 2'b11
`define DUTY_ADDR 2'b01

`define CMD_ADDR_SIZE 2
`define CMD_DATA_IN_SIZE 16
`define CMD_DATA_OUT_SIZE 16
`define PERIOD_SIZE 16
`define DUTY_SIZE 16
`define PRESCALER_SIZE 3